"""Split static/js/i18n-data.js into one file per language.

i18n-data.js ships all 12 languages (~370 KB) to every visitor, who reads
exactly one of them. This splits it into:

    static/js/i18n-langs.js      the LANGUAGES list only (~1 KB, loaded always)
    static/js/i18n/<code>.js     one language's TRANSLATIONS table (~30 KB)

i18n.js then fetches only the active language (plus English as the fallback
table). i18n-data.js stays as the editable source of truth — re-run this
script after changing it:

    python scripts/split_i18n_data.py

The split is pure text slicing on the file's existing block layout; it never
evaluates the file, so a translation containing braces or quotes can't confuse
it as long as the source keeps one `<code>: {` block per language at the
standard indent.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'static', 'js', 'i18n-data.js')
LANGS_OUT = os.path.join(ROOT, 'static', 'js', 'i18n-langs.js')
LANG_DIR = os.path.join(ROOT, 'static', 'js', 'i18n')

LANG_BLOCK_INDENT = ' ' * 8
LANGUAGE_ENTRY = re.compile(r"\{\s*code:\s*'([^']+)'")

HEADER = "/* Generated by scripts/split_i18n_data.py — edit i18n-data.js instead. */\n"


def read_source() -> list[str]:
    with open(SOURCE, encoding='utf-8') as handle:
        return handle.read().splitlines(keepends=True)


def language_list(lines: list[str]) -> tuple[list[str], str]:
    """The declared language codes, plus the verbatim `const LANGUAGES = [...]`
    block so the generated langs file stays byte-identical to the source."""
    start = next(i for i, line in enumerate(lines) if line.startswith('    const LANGUAGES'))
    end = next(i for i in range(start, len(lines)) if lines[i].rstrip() == '    ];')
    block = ''.join(lines[start : end + 1])
    return LANGUAGE_ENTRY.findall(block), block


def language_blocks(lines: list[str], codes: list[str]) -> dict[str, str]:
    """{code: "<the object literal body, without the trailing comma>"}."""
    starts: dict[str, int] = {}
    for index, line in enumerate(lines):
        for code in codes:
            if line.startswith(f'{LANG_BLOCK_INDENT}{code}: {{'):
                starts.setdefault(code, index)
    missing = [code for code in codes if code not in starts]
    if missing:
        raise SystemExit(f'No translation block found for: {", ".join(missing)}')

    ordered = sorted(starts.items(), key=lambda pair: pair[1])
    end_of_table = next(i for i in range(len(lines) - 1, -1, -1) if lines[i].rstrip() == '    };')

    blocks: dict[str, str] = {}
    for position, (code, start) in enumerate(ordered):
        stop = ordered[position + 1][1] if position + 1 < len(ordered) else end_of_table
        body = ''.join(lines[start:stop]).rstrip()
        # Each block reads "<code>: { ... }" and (except the last) ends with a
        # comma separating it from the next language. Strip both wrappers so
        # what's left is a standalone object literal.
        body = body[len(f'{LANG_BLOCK_INDENT}{code}: ') :]
        if body.endswith(','):
            body = body[:-1]
        blocks[code] = body
    return blocks


def main() -> int:
    if not os.path.exists(SOURCE):
        print(f'Missing source file: {SOURCE}')
        return 1
    lines = read_source()
    codes, languages_block = language_list(lines)
    blocks = language_blocks(lines, codes)

    os.makedirs(LANG_DIR, exist_ok=True)

    with open(LANGS_OUT, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(HEADER)
        handle.write('(function (global) {\n    \'use strict\';\n\n')
        handle.write(languages_block)
        handle.write('\n    global.I18N = global.I18N || { LANGUAGES: [], TRANSLATIONS: {} };\n')
        handle.write('    global.I18N.LANGUAGES = LANGUAGES;\n')
        handle.write('})(window);\n')

    written = 0
    for code, body in blocks.items():
        path = os.path.join(LANG_DIR, f'{code}.js')
        with open(path, 'w', encoding='utf-8', newline='\n') as handle:
            handle.write(HEADER)
            handle.write('(function (global) {\n    \'use strict\';\n')
            handle.write('    global.I18N = global.I18N || { LANGUAGES: [], TRANSLATIONS: {} };\n')
            handle.write(f'    global.I18N.TRANSLATIONS[\'{code}\'] = ')
            handle.write(body.strip())
            handle.write(';\n})(window);\n')
        written += 1
        print(f'  {code}.js  {os.path.getsize(path) // 1024} KB')

    print(f'\nWrote {written} language files to static/js/i18n/ plus i18n-langs.js.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
